package com.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGamematch<M extends BaseGamematch<M>> extends Model<M> implements IBean {

	public void setMatchId(java.lang.String matchId) {
		set("matchId", matchId);
	}

	public java.lang.String getMatchId() {
		return get("matchId");
	}

	public void setMatchType(java.lang.String matchType) {
		set("matchType", matchType);
	}

	public java.lang.String getMatchType() {
		return get("matchType");
	}

	public void setGameTime(java.lang.String gameTime) {
		set("gameTime", gameTime);
	}

	public java.lang.String getGameTime() {
		return get("gameTime");
	}

	public void setEndTime(java.util.Date endTime) {
		set("endTime", endTime);
	}

	public java.util.Date getEndTime() {
		return get("endTime");
	}

	public void setRecord(java.lang.String record) {
		set("record", record);
	}

	public java.lang.String getRecord() {
		return get("record");
	}

	public void setGoldRate(java.lang.String goldRate) {
		set("goldRate", goldRate);
	}

	public java.lang.String getGoldRate() {
		return get("goldRate");
	}

}
