package com.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGamedetails<M extends BaseGamedetails<M>> extends Model<M> implements IBean {

	public void setDetailId(java.lang.Integer detailId) {
		set("detailId", detailId);
	}

	public java.lang.Integer getDetailId() {
		return get("detailId");
	}

	public void setMatchId(java.lang.String matchId) {
		set("matchId", matchId);
	}

	public java.lang.String getMatchId() {
		return get("matchId");
	}

	public void setFloor(java.lang.String floor) {
		set("floor", floor);
	}

	public java.lang.String getFloor() {
		return get("floor");
	}

	public void setServerName(java.lang.String serverName) {
		set("serverName", serverName);
	}

	public java.lang.String getServerName() {
		return get("serverName");
	}

	public void setPlayerName(java.lang.String playerName) {
		set("playerName", playerName);
	}

	public java.lang.String getPlayerName() {
		return get("playerName");
	}

	public void setEarn(java.lang.String earn) {
		set("earn", earn);
	}

	public java.lang.String getEarn() {
		return get("earn");
	}

	public void setKDA(java.lang.String KDA) {
		set("KDA", KDA);
	}

	public java.lang.String getKDA() {
		return get("KDA");
	}

	public void setEquip1(java.lang.String equip1) {
		set("equip1", equip1);
	}

	public java.lang.String getEquip1() {
		return get("equip1");
	}

	public void setEquip2(java.lang.String equip2) {
		set("equip2", equip2);
	}

	public java.lang.String getEquip2() {
		return get("equip2");
	}

	public void setEquip3(java.lang.String equip3) {
		set("equip3", equip3);
	}

	public java.lang.String getEquip3() {
		return get("equip3");
	}

	public void setEquip4(java.lang.String equip4) {
		set("equip4", equip4);
	}

	public java.lang.String getEquip4() {
		return get("equip4");
	}

	public void setEquip5(java.lang.String equip5) {
		set("equip5", equip5);
	}

	public java.lang.String getEquip5() {
		return get("equip5");
	}

	public void setEquip6(java.lang.String equip6) {
		set("equip6", equip6);
	}

	public java.lang.String getEquip6() {
		return get("equip6");
	}

	public void setEquip7(java.lang.String equip7) {
		set("equip7", equip7);
	}

	public java.lang.String getEquip7() {
		return get("equip7");
	}

	public void setMinionsKilled(java.lang.Integer minionsKilled) {
		set("minionsKilled", minionsKilled);
	}

	public java.lang.Integer getMinionsKilled() {
		return get("minionsKilled");
	}

	public void setMinionsKDA(java.lang.String minionsKDA) {
		set("minionsKDA", minionsKDA);
	}

	public java.lang.String getMinionsKDA() {
		return get("minionsKDA");
	}

	public void setSummonerSkill1(java.lang.String summonerSkill1) {
		set("summonerSkill1", summonerSkill1);
	}

	public java.lang.String getSummonerSkill1() {
		return get("summonerSkill1");
	}

	public void setSummonerSkill2(java.lang.String summonerSkill2) {
		set("summonerSkill2", summonerSkill2);
	}

	public java.lang.String getSummonerSkill2() {
		return get("summonerSkill2");
	}

	public void setKDARating(java.lang.String KDARating) {
		set("KDARating", KDARating);
	}

	public java.lang.String getKDARating() {
		return get("KDARating");
	}

	public void setChampionUsed(java.lang.String championUsed) {
		set("championUsed", championUsed);
	}

	public java.lang.String getChampionUsed() {
		return get("championUsed");
	}

	public void setKilled(java.lang.Integer Killed) {
		set("Killed", Killed);
	}

	public java.lang.Integer getKilled() {
		return get("Killed");
	}

	public void setMonsterKilled(java.lang.Integer monsterKilled) {
		set("monsterKilled", monsterKilled);
	}

	public java.lang.Integer getMonsterKilled() {
		return get("monsterKilled");
	}

	public void setDownTower(java.lang.Integer downTower) {
		set("downTower", downTower);
	}

	public java.lang.Integer getDownTower() {
		return get("downTower");
	}

	public void setDownBarrack(java.lang.Integer downBarrack) {
		set("downBarrack", downBarrack);
	}

	public java.lang.Integer getDownBarrack() {
		return get("downBarrack");
	}

	public void setPlaceGuard(java.lang.Integer placeGuard) {
		set("placeGuard", placeGuard);
	}

	public java.lang.Integer getPlaceGuard() {
		return get("placeGuard");
	}

	public void setWipeGuard(java.lang.Integer wipeGuard) {
		set("wipeGuard", wipeGuard);
	}

	public java.lang.Integer getWipeGuard() {
		return get("wipeGuard");
	}

	public void setHighestKill(java.lang.Integer highestKill) {
		set("highestKill", highestKill);
	}

	public java.lang.Integer getHighestKill() {
		return get("highestKill");
	}

	public void setPentaKill(java.lang.Integer pentaKill) {
		set("pentaKill", pentaKill);
	}

	public java.lang.Integer getPentaKill() {
		return get("pentaKill");
	}

	public void setHighestCrit(java.lang.Integer highestCrit) {
		set("highestCrit", highestCrit);
	}

	public java.lang.Integer getHighestCrit() {
		return get("highestCrit");
	}

	public void setTotalHeal(java.lang.Integer totalHeal) {
		set("totalHeal", totalHeal);
	}

	public java.lang.Integer getTotalHeal() {
		return get("totalHeal");
	}

	public void setFinalDamage(java.lang.Integer finalDamage) {
		set("finalDamage", finalDamage);
	}

	public java.lang.Integer getFinalDamage() {
		return get("finalDamage");
	}

	public void setBear(java.lang.Integer bear) {
		set("bear", bear);
	}

	public java.lang.Integer getBear() {
		return get("bear");
	}

	public void setDamageToChampion(java.lang.Integer damageToChampion) {
		set("damageToChampion", damageToChampion);
	}

	public java.lang.Integer getDamageToChampion() {
		return get("damageToChampion");
	}

	public void setMagicDamage(java.lang.Integer magicDamage) {
		set("magicDamage", magicDamage);
	}

	public java.lang.Integer getMagicDamage() {
		return get("magicDamage");
	}

	public void setPhysicalDamage(java.lang.Integer physicalDamage) {
		set("physicalDamage", physicalDamage);
	}

	public java.lang.Integer getPhysicalDamage() {
		return get("physicalDamage");
	}

	public void setTrueDamage(java.lang.Integer trueDamage) {
		set("trueDamage", trueDamage);
	}

	public java.lang.Integer getTrueDamage() {
		return get("trueDamage");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
