package com.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseChampion<M extends BaseChampion<M>> extends Model<M> implements IBean {

	public void setChampionId(java.lang.Integer championId) {
		set("championId", championId);
	}

	public java.lang.Integer getChampionId() {
		return get("championId");
	}

	public void setServerName(java.lang.String serverName) {
		set("serverName", serverName);
	}

	public java.lang.String getServerName() {
		return get("serverName");
	}

	public void setPlayerName(java.lang.String playerName) {
		set("playerName", playerName);
	}

	public java.lang.String getPlayerName() {
		return get("playerName");
	}

	public void setChampionName(java.lang.String championName) {
		set("championName", championName);
	}

	public java.lang.String getChampionName() {
		return get("championName");
	}

	public void setMatchStat(java.lang.Integer matchStat) {
		set("matchStat", matchStat);
	}

	public java.lang.Integer getMatchStat() {
		return get("matchStat");
	}

	public void setWinRate(java.math.BigDecimal winRate) {
		set("winRate", winRate);
	}

	public java.math.BigDecimal getWinRate() {
		return get("winRate");
	}

	public void setAverageKDA(java.lang.String averageKDA) {
		set("averageKDA", averageKDA);
	}

	public java.lang.String getAverageKDA() {
		return get("averageKDA");
	}

	public void setAverageKDARating(java.lang.String averageKDARating) {
		set("averageKDARating", averageKDARating);
	}

	public java.lang.String getAverageKDARating() {
		return get("averageKDARating");
	}

	public void setAverageDamage(java.lang.Integer averageDamage) {
		set("averageDamage", averageDamage);
	}

	public java.lang.Integer getAverageDamage() {
		return get("averageDamage");
	}

	public void setAverageEarn(java.lang.Integer averageEarn) {
		set("averageEarn", averageEarn);
	}

	public java.lang.Integer getAverageEarn() {
		return get("averageEarn");
	}

	public void setAverageMinionsKilled(java.lang.Integer averageMinionsKilled) {
		set("averageMinionsKilled", averageMinionsKilled);
	}

	public java.lang.Integer getAverageMinionsKilled() {
		return get("averageMinionsKilled");
	}

	public void setTotalMVP(java.lang.Integer totalMVP) {
		set("totalMVP", totalMVP);
	}

	public java.lang.Integer getTotalMVP() {
		return get("totalMVP");
	}

	public void setTotalHope(java.lang.Integer totalHope) {
		set("totalHope", totalHope);
	}

	public java.lang.Integer getTotalHope() {
		return get("totalHope");
	}

	public void setDuowanUpdateTime(java.util.Date duowanUpdateTime) {
		set("duowanUpdateTime", duowanUpdateTime);
	}

	public java.util.Date getDuowanUpdateTime() {
		return get("duowanUpdateTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
