package com.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlayer<M extends BasePlayer<M>> extends Model<M> implements IBean {

	public void setPlayerId(java.lang.Integer playerId) {
		set("playerId", playerId);
	}

	public java.lang.Integer getPlayerId() {
		return get("playerId");
	}

	public void setPlayerName(java.lang.String playerName) {
		set("playerName", playerName);
	}

	public java.lang.String getPlayerName() {
		return get("playerName");
	}

	public void setServerName(java.lang.String serverName) {
		set("serverName", serverName);
	}

	public java.lang.String getServerName() {
		return get("serverName");
	}

	public void setStrength(java.lang.Integer strength) {
		set("strength", strength);
	}

	public java.lang.Integer getStrength() {
		return get("strength");
	}

}
