package com.common.model;

import com.common.model.base.BaseChampion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Champion extends BaseChampion<Champion> {
	public static final Champion dao = new Champion();
}
