package com.common.model;

import com.common.model.base.BaseEquip;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Equip extends BaseEquip<Equip> {
	public static final Equip dao = new Equip();
}
