package com.common.model;

import com.common.model.base.BaseGamematch;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Gamematch extends BaseGamematch<Gamematch> {
	public static final Gamematch dao = new Gamematch();
	public Gamematch findMatchByMatchId(String matchId){
		return dao.findFirst("SELECT * FROM `gamematch` where matchId = ?",matchId);
	}
}
