package com.common.model;

import com.common.model.base.BaseGamedetails;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Gamedetails extends BaseGamedetails<Gamedetails> {
	public static final Gamedetails dao = new Gamedetails();
	
	public Gamedetails findByPSName(String playerName,String serverName,String matchId) {
		String sql="select * from `gamedetails` where `playerName`= ? and `serverName`= ? and `matchId`= ?";
		return dao.findFirst(sql,playerName,serverName,matchId);
	}
	
//	public List<Integer> findDetailStatus(String playerName,String serverName) {
//		String sql = "SELECT status FROM gamedetails where playerName = ? and serverName = ?";
//		List<Gamedetails> status= dao.find(sql,playerName,serverName);
//		List<Integer> statuss=new ArrayList<Integer>();
//		for (Gamedetails gamedetails : status) {
//			statuss.add(gamedetails.getStatus());
//		}
//		return statuss;
//	}
}
