package com.common.model;

import com.common.model.base.BasePlayer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Player extends BasePlayer<Player> {
	public static final Player dao = new Player();
}
